### PR TITLE
feat: add support for nuxt link locale from i18n

### PR DESCRIPTION
**Pull request by UfukUstali**
For the types for the [NuxtLinkLocale](https://github.com/nuxt-modules/i18n/blob/main/src/runtime/components/NuxtLinkLocale.ts) component to be generated correctly this module needs to be loaded after the i18n module. This is because of how we detect if this component exists in th first place. (see module.ts file)

I did try the following to avoid this:
- could **not** import component directly because the exports are locked down by the [package.json](https://github.com/nuxt-modules/i18n/blob/main/package.json#L25-L32) file of the i18n repo (node complains at runtime) and the allowed files do not export the component (I don't know if there is a workaround)
- could **not** use the \#components file because it is not generated yet
- could **not** use the \#components file in the file that we generate to conditionally set the type to undefined because of how import/declare order goes around

Conditional generation and/or declaration of the types is required because this component was introduced on July 31. in the [v8.0.0-rc.1](https://github.com/nuxt-modules/i18n/releases/tag/v8.0.0-rc.1) relase. If it is fine to include the types by default then all of the above can be safely ignored and changes can be made accordingly.

### CODE REVIEW

**Comment by victorgarciaesgi** [comment]
Also do you mind trying to add unit type tests? :)
Either on `test/fixtures/complex/tests/i18n` or `test/fixtures/complex/src/pages/index.vue`!

**Comment by victorgarciaesgi** [comment]
Upgraded the workflow engine to node 18, you can rebase for the tests to run

**Comment by UfukUstali** [comment]
So I did try to get tests to work but upgrading the the \@nuxtjs/i18n to a version that has the NuxtLinkLocale component broke other parts, mainly `vueI18n` configuration had to be in it's own file now and `NuxtI18nOptions` type was not exported anymore. (I still don't know how to fix the latter).

**Comment by UfukUstali** [comment]
resolved with #128

**Pull request closed without merging**
